import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { readFlow, writeFlow, post } from "../lib/crispFlow";
function Critique(){const navigate=useNavigate();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const flow=readFlow();const c=flow?.critique;
async function refine(){setLoading(true);setError("");try{const result=await post("/api/refine",{question:flow.question,initial_response:flow.initialResponse,evaluation:flow.initialEvaluation,decision:flow.decision});writeFlow({...flow,refinement:result,timings:{...(flow.timings||{}),refine:result.duration_seconds||0},stage:5});navigate("/refinement")}catch(e){setError(e.message)}finally{setLoading(false)}}
return <div className="space-y-8"><div><h1 className="text-3xl font-bold text-white">Response Critique</h1><p className="mt-2 text-slate-400">Strengths, areas for improvement, and actionable suggestions based on the actual evaluation.</p></div>{!c?<Empty/>:<><Section title="Strengths" items={c.strengths}/><Section title="Areas for Improvement" items={c.areas_for_improvement}/><Section title="Suggestions for Refinement" items={c.suggestions}/><div className="flex justify-end"><button disabled={loading} onClick={refine} className="rounded-lg bg-purple-600 px-6 py-3 font-semibold text-white hover:bg-purple-700 disabled:opacity-50">{loading?"Refining response...":"Response Refinement →"}</button></div>{error&&<p className="text-sm text-red-400">{error}</p>}</>}</div>}
function Section({title,items}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-white">{title}</h2>{!items?.length?<p className="mt-4 text-slate-400">No items returned.</p>:<ul className="mt-4 space-y-3">{items.map((x,i)=><li key={i} className="rounded-xl border border-slate-800 bg-slate-950 p-4 leading-7 text-slate-300">{x}</li>)}</ul>}</div>}
function Empty(){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 text-slate-400">No critique available. Continue from the adaptive decision page first.</div>}
export default Critique;
